[features]
seeds = false
skip-lint = false
[programs.localnet]
shop_manager = "8agPo1zq2ZvXLqsgH5RuhxFJGJrsPTSSopZiYixYJXZy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/justice/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
